# Copyright (C) 2026 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("../../nearlink_config.gni")

service_cflags = [
    "-fPIC",
    "-Wno-format",
    "-Wno-pessimizing-move",
    "-Wno-unused-parameter",
    "-Wreorder",
    "-Wmissing-braces",
    "-Wimplicit-fallthrough",
    "-Wlogical-op-parentheses",
    "-Wmissing-field-initializers",
    "-Wparentheses-equality",
    "-Wparentheses",
    "-Wdelete-non-abstract-non-virtual-dtor",
    "-Wignored-qualifiers",
    "-Wdelete-abstract-non-virtual-dtor",
    "-Wuninitialized",
    "-Woverloaded-virtual",
    "-Wdangling-else",
    "-Woverloaded-virtual",
    "-Wno-non-c-typedef-for-linkage",
    "-Wno-unused-but-set-variable",
    "-Wno-array-parameter",
    "-Wno-unused-lambda-capture",
    "-fdata-sections",
    "-ffunction-sections",
    "-fno-asynchronous-unwind-tables",
    "-fno-unwind-tables",
    "-Os",
    "-fno-exceptions",
    "-fno-rtti",
    "-flto",
  ]

config("nearlink_service_config") {
  cflags = service_cflags

  if (build_variant == "user") {
    cflags += [ "-DIS_NL_RELEASE_VERSION" ]
  }

  cflags_cc = cflags

  include_dirs = [
    "include",
    "common",
    "src/common",
    "src/util",
    "src/base",
    "src/powermgr",
    "src/adapter",
    "src/advertiser",
    "src/adapter/sle_scan_filter/include",
    "src/hadm",
    "src/hid",
    "src/ssap",
    "src/ipshare",
    "src/controllerManager",
    "src/datatransfer",
    "src/dis",
    "src/lis",
    "src/icce",
    "src/datashare",
    "src/scan",
    "src/dialog",
    "src/port",
    "src/cdsm",
    "src/mcp",
    "src/sl_host",
    "src/tws",
    "src/vcp",
    "src/asc",
    "src/bas",
    "src/ccp",
    "src/vas",
    "src/cloudpair",
    "src/mic",
    "src/audio",
    "src/ServiceManagerPluginLoader",
    "src/controller",
  ]
}

config("nearlink_service_public_config") {
  include_dirs = [
    "include",
  ]
}

########################### nearlink_service source deps and external_deps classify ###########################

ServiceCommonSrc = [
  "src/common/AdapterStateMachine.cpp",
  "src/common/ClassCreator.cpp",
  "src/common/Compat.cpp",
  "src/common/ProfileInfo.cpp",
  "src/common/ProfileServiceManager.cpp",
  "src/common/SleServiceManager.cpp",
  "src/common/SleCollaborationManager.cpp",
  "src/common/SleHiviewUe.cpp",
  "src/common/SleCommonEventSubscriber.cpp",
  "src/common/SleSwitchDependency.cpp",
  "src/common/SysStateMachine.cpp",
  "src/common/SleMultiScanData.cpp",
  "src/common/SleFrame4AntennaMgr.cpp",
  "src/common/DeviceBatteryManager.cpp",
  "src/common/UnloadSa.cpp",
]

ServiceAdapterSrc = [
  "src/adapter/SleAdapterWrapper.cpp",
  "src/adapter/SleAdapter.cpp",
  "src/adapter/SleRemoteDeviceAdapter.cpp",
  "src/adapter/SleCoexist.cpp",
  "src/adapter/SleProperties.cpp",
  "src/adapter/SleSecurity.cpp",
  "src/adapter/SleProfileConnectManager.cpp",
  "src/adapter/SleFeature.cpp",
  "src/adapter/SleReconnectManager.cpp",
]

ServiceAdvertiserSrc = [
  "src/advertiser/SleAdvertiserAdapter.cpp",
  "src/advertiser/SleAdvertiserImpl.cpp",
]

ServiceScanSrc = [
  "src/scan/ScanService.cpp",
  "src/scan/ScanStackAdapter.cpp",
]

ServiceSsapSrc = [
  "src/ssap/ssap_client_service.cpp",
  "src/ssap/ssap_client_stack_adapter.cpp",
  "src/ssap/ssap_server_service.cpp",
  "src/ssap/ssap_server_stack_adapter.cpp",
  "src/ssap/ssap_utils.cpp",
  "src/ssap/ssap_based_services_manager.cpp",
  "src/ipshare/iposl_ssap_probe.cpp",
]

ServiceHidSrc = [
  "src/hid/HidHostService.cpp",
  "src/hid/HidHostStackAdapter.cpp",
  "src/hid/HidHostUhid.cpp",
]

ServiceHadmSrc = [
  "src/hadm/nearlink_hadm_stack_adapter.cpp",
  "src/hadm/nearlink_hadm_client_service.cpp",
]

ServiceDisSrc = [
  "src/dis/DisService.cpp",
  "src/dis/DisClientStackAdapter.cpp",
  "src/dis/DisServerStackAdapter.cpp",
]

ServiceBasSrc = [
  "src/bas/BasService.cpp",
  "src/bas/BasClientStackAdapter.cpp",
]

ServiceLisSrc = [
  "src/lis/LisService.cpp",
  "src/lis/LisServer.cpp",
]

ServiceIcceSrc = [
  "src/icce/IcceService.cpp",
  "src/icce/IcceClientStackAdapter.cpp",
  "src/icce/IcceServerStackAdapter.cpp",
  "src/icce/icce_utils.cpp",
]

ServiceDatashareSrc = [
  "src/datashare/nearlink_datashare_helper.cpp",
  "src/datashare/SleNameChangeManager.cpp",
]

ServiceDatatransferSrc = [
  "src/datatransfer/nearlink_sle_datatransfer_cache.cpp",
  "src/datatransfer/nearlink_sle_datatransfer_service.cpp",
]

ServicePortSrc = [
  "src/port/PortService.cpp",
  "src/port/PortClientStackAdapter.cpp",
  "src/port/PortServerStackAdapter.cpp",
]

ServiceDialogSrc = [
  "src/dialog/DialogGenerate.cpp",
  "src/dialog/DialogPairing.cpp",
  "src/dialog/DialogUtils.cpp",
]

ServiceCdsmSrc = [
  "src/cdsm/CdsmService.cpp",
  "src/cdsm/CdsmClient.cpp",
]

ServiceTwsSrc = [
  "src/tws/TwsClient.cpp",
  "src/tws/TwsService.cpp",
  "src/tws/TwsHiBoxParser.cpp",
  "src/tws/TwsSharedLibApi.cpp",
]

ServiceCloudpairSrc = [
  "src/cloudpair/SleCloudPairService.cpp",
]

ServiceMcpSrc = [
  "src/mcp/McpServerServiceManagerLoader.cpp",
]

ServicePluginLoaderSrc = [
  "src/ServiceManagerPluginLoader/ServiceManagerPluginLoader.cpp",
]

ServiceControllerSrc = [
  "src/controller/SleControllerService.cpp",
]

nearlink_service_sources = ServiceCommonSrc
nearlink_service_sources += ServiceAdapterSrc
nearlink_service_sources += ServiceAdvertiserSrc
nearlink_service_sources += ServiceScanSrc
nearlink_service_sources += ServiceSsapSrc
nearlink_service_sources += ServiceHidSrc
nearlink_service_sources += ServiceHadmSrc
nearlink_service_sources += ServiceDisSrc
nearlink_service_sources += ServiceBasSrc
nearlink_service_sources += ServiceLisSrc
nearlink_service_sources += ServiceIcceSrc
nearlink_service_sources += ServiceDatashareSrc
nearlink_service_sources += ServiceDatatransferSrc
nearlink_service_sources += ServicePortSrc
nearlink_service_sources += ServiceDialogSrc
nearlink_service_sources += ServiceCdsmSrc
nearlink_service_sources += ServiceTwsSrc
nearlink_service_sources += ServiceCloudpairSrc
nearlink_service_sources += ServiceMcpSrc
nearlink_service_sources += ServicePluginLoaderSrc
nearlink_service_sources += ServiceControllerSrc

nearlink_service_deps = [
  "$NEARLINK_ROOT/services/stack:nearlink_stack",
  "$NEARLINK_ROOT/services/stack/src/sdf:nearlink_stack_sdf",
  "$NEARLINK_ROOT/utils:nearlink_utils",
  "$NEARLINK_ROOT/socket:nearlink_socket",
  "$NEARLINK_ROOT/ipc_parcel:nearlink_ipc_parcel",
  "$NEARLINK_ROOT/services/common:nearlink_service_common",
  "$NEARLINK_ROOT/services/dft:nearlink_dft_manager",
  "$NEARLINK_ROOT/services/device_manager:nearlink_device_manager",
  "$NEARLINK_ROOT/services/hardware:nearlink_dli_adapter",
]

nearlink_service_external_deps = [
  "ability_base:want",
  "ability_base:zuri",
  "ability_runtime:extension_manager",
  "access_token:libaccesstoken_sdk",
  "access_token:libtokenid_sdk",
  "access_token:libprivacy_sdk",
  "c_utils:utils",
  "cJSON:cjson",
  "ffrt:libffrt",
  "hilog:libhilog",
  "huks:libhukssdk",
  "init:libbegetutil",
  "init:libbeget_proxy",
  "ipc:ipc_core",
  "samgr:samgr_proxy",
  "data_share:datashare_common",
  "data_share:datashare_consumer",
  "ability_runtime:wantagent_innerkits",
  "ability_runtime:ability_connect_callback_stub",
  "time_service:time_client",
  "os_account:os_account_innerkits",
  "qos_manager:qos",
  "openssl:libcrypto_shared",
  "os_account:libaccountkits",
  "openssl:libcrypto_shared",
  "os_account:libaccountkits",
  "hisysevent:libhisysevent",
  "hisysevent:libhisyseventmanager",
  "bundle_framework:appexecfwk_core",
]

nearlink_service_defines = []

########################### nearlink_service feture ###########################

if (nearlink_service_kia_enable) {
  nearlink_service_external_deps += [ "security_guard:libsg_collect_sdk" ]
  nearlink_service_defines += [ "NEARLINK_KIA_ENABLE" ]
}

if (nearlink_service_edm_enable) {
  nearlink_service_sources += [
    "src/common/SleEdmManager.cpp",
  ]
  nearlink_service_defines += [ "NEARLINK_EDM_ENABLE" ]
}

if (nearlink_service_host_dynamic_running) {
  nearlink_service_external_deps += [ "hdf_core:libhdi" ]
  nearlink_service_defines += ["NEARLINK_HOST_DYNAMIC_RUNING"]
}

if (nearlink_service_no_pairing_dialog) {
  nearlink_service_defines += ["NO_PAIRING_DIALOG"]
}

if (nearlink_service_sync_ap_to_mcu) {
    nearlink_service_defines += ["NEARLINK_SYNC_AP_TO_MCU"]
}

if (nearlink_service_min_conn_interval != 0) {
    nearlink_service_defines += [ "MIN_CONN_INTERVAL=${nearlink_service_min_conn_interval}" ]
}

########################### nearlink_service 弱耦合部件依赖 ###########################

if (nearlink_deps_audio_exist) {
  nearlink_service_sources += [
    "src/mcp/McpServerService.cpp",
    "src/asc/ASCService.cpp",
    "src/asc/QosM.cpp",
    "src/asc/ASCUtils.cpp",
    "src/adapter/SleASC.cpp",
    "src/vcp/VcpService.cpp",
    "src/vcp/VcpStackAdapter.cpp",
    "src/mic/MicService.cpp",
    "src/mic/MicClientStackAdapter.cpp",
    "src/audio/SleAudioFrameworkAdapter.cpp",
  ]
  nearlink_service_external_deps += [
    "audio_framework:audio_policy_manager",
    "audio_framework:audio_engine_manager",
    "audio_framework:audio_foundation",
  ]
}

if (nearlink_deps_telephony_exist) {
  nearlink_service_sources += [
      "src/ccp/CcpService.cpp",
      "src/ccp/CcpStackAdapter.cpp",
      "src/ccp/CcpSystemInterface.cpp",
      "src/vas/VasService.cpp",
      "src/vas/VasStackAdapter.cpp",
    ]
  nearlink_service_external_deps += [
    "call_manager:tel_call_manager_api",
    "core_service:tel_core_service_api",
    "state_registry:tel_state_registry_api",
  ]
}

if (nearlink_deps_device_manager_exist) {
  nearlink_service_external_deps += [ "device_manager:devicemanagersdk" ]
  nearlink_service_defines += ["DEVICE_MANAGER"]
}

########################### nearlink_service feature && 弱耦合部件依赖 && 其他 ###########################

if (nearlink_deps_resource_schedule_service_exist && nearlink_service_rss_background_task) {
  nearlink_service_external_deps += [ "resource_schedule_service:ressched_client" ]
  nearlink_service_defines += [ "RES_SCHED_SUPPORT" ]
}

if (factory == true) {
  nearlink_service_defines += ["CONFIG_FACTORY_VERSION"]
}

nearlink_service_defines += product_defines

########################### nearlink_service_impl ###########################

ohos_shared_library("nearlink_service_impl") {
  branch_protector_ret = "pac_ret"

  ldflags = [
    "-flto",
    "-Wl,--gc-sections",
  ]

  sanitize = {
      cfi = true                             # Enable/disable control flow integrity detection
      cfi_vcall_icall_only = true            # CFI optimization, limit CFI check scope
      boundary_sanitize = true               # Enable boundary san detection
      cfi_cross_dso = true                   # Cross-SO CFI Checks
      integer_overflow = true                # Enable integer overflow detection
      ubsan = true                           # Enable some Ubsan options
      debug = false
      blocklist = "./libsleservice_blocklist.txt"
  }

  configs = [ ":nearlink_service_config" ]
  public_configs = [ ":nearlink_service_public_config" ]

  sources = nearlink_service_sources
  deps = nearlink_service_deps
  external_deps = nearlink_service_external_deps

  defines =  [
    "LOG_TAG = \"nearlink_service\"",
    "LOG_DOMAIN = 0xD000152",
  ]
  defines += nearlink_service_defines

  subsystem_name = "communication"
  part_name = "nearlink_service"
}

########################### nearlink_service_impl ###########################
# Only use for fuzztest
ohos_static_library("nearlink_service_impl_static") {
  branch_protector_ret = "pac_ret"  # Enable PAC CFI
  sanitize = {
    cfi = true                             # Enable/disable control flow integrity detection
    cfi_cross_dso = true                   # Cross-SO CFI Checks
    debug = false
  }

  configs = [ ":nearlink_service_config" ]
  public_configs = [ ":nearlink_service_public_config" ]

  sources = nearlink_service_sources
  deps = nearlink_service_deps
  external_deps = nearlink_service_external_deps

  defines =  [
    "LOG_TAG = \"nearlink_service\"",
    "LOG_DOMAIN = 0xD000152",
  ]
  defines += nearlink_service_defines

  subsystem_name = "communication"
  part_name = "nearlink_service"
}

########################### mcp_manager ###############################
config("nearlink_mcp_manager_config") {
  cflags = service_cflags

  if (build_variant == "user") {
    cflags += [ "-DIS_NL_RELEASE_VERSION" ]
  }

  cflags_cc = cflags

  include_dirs = [
    "src/base",
    "src/common",
    "src/util",
    "src/mcp",
    "include",
  ]
}

ohos_shared_library("nearlink_mcp_manager") {
  branch_protector_ret = "pac_ret"  # Enable PAC CFI
  stack_protector_ret = false
  
  ldflags = [
    "-flto",
    "-Wl,--gc-sections",
  ]

  sanitize = {
      cfi = true                             # Enable/disable control flow integrity detection
      cfi_vcall_icall_only = true            # CFI optimization, limit CFI check scope
      boundary_sanitize = true               # Enable boundary san detection
      cfi_cross_dso = true                   # Cross-SO CFI Checks
      integer_overflow = true                # Enable integer overflow detection
      ubsan = true                           # Enable some Ubsan options
      debug = false
  }

  configs = [ ":nearlink_mcp_manager_config" ]

  # Used to control the export of dynamic library symbols.
  version_script = "libnearlink_mcp_service.versionscript"

  deps = [
    "$NEARLINK_ROOT/services/stack:nearlink_stack",
    "$NEARLINK_ROOT/utils:nearlink_utils",
    "$NEARLINK_ROOT/ipc_parcel:nearlink_ipc_parcel",
    "$NEARLINK_ROOT/services/dft:nearlink_dft_manager",
    "$NEARLINK_ROOT/services/common:nearlink_service_common",
    "$NEARLINK_ROOT/services/device_manager:nearlink_device_manager",
    "$NEARLINK_ROOT/services/stack/src/sdf:nearlink_stack_sdf",
  ]

  external_deps = [
    "hilog:libhilog",
    "ability_base:want",
    "hisysevent:libhisysevent",
    "hisysevent:libhisyseventmanager",
  ]
  sources = []

  if (nearlink_deps_audio_exist) {
    external_deps += [
      "ability_runtime:wantagent_innerkits",
      "av_session:avsession_client",
      "audio_framework:audio_policy_manager",
      "audio_framework:audio_engine_manager",
      "audio_framework:audio_foundation",
      "input:libmmi-client",
      "ipc:ipc_core",
      "c_utils:utils",
    ]
  }

  if (nearlink_deps_audio_exist) {
    sources += [
      "src/mcp/McpServerServiceManager.cpp",
    ]
  }

   subsystem_name = "communication"
   part_name = "nearlink_service"
}
