# Copyright (C) 2026 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/test.gni")
import("../../../../../nearlink_config.gni")
import("../../../../../test/utils/test_utils.gni")

config("nl_ssap_server_service_unit_test_config") {
  visibility = [ ":*" ]

  include_dirs = [
    "$NEARLINK_ROOT/services/common/include",
    "$NEARLINK_ROOT/services/service/src/util",
    "$NEARLINK_ROOT/services/service/src/adapter",
    "$NEARLINK_ROOT/services/service/src/ssap",
    "$NEARLINK_ROOT/services/service/src/ipshare",
    "$NEARLINK_ROOT/services/service/src/common",
    "$NEARLINK_ROOT/services/service/src/base",
    "$NEARLINK_ROOT/services/service/src/lis",
    "$NEARLINK_ROOT/services/server/include",
    "$NEARLINK_ROOT/services/ipc/include",
    "$NEARLINK_ROOT/services/stack/src/cp/bsl/sle/servm/ssap/include",
    "$NEARLINK_ROOT/test/unittest/mock",
  ]

  defines =  [
    "LOG_TAG = \"nearlink_test\"",
    "LOG_DOMAIN = 0xD000151",
    "private = public"
  ]
  cflags_cc = [ "-fexceptions" ]
  cflags = [ "--coverage" ]
  ldflags = [ "--coverage" ]
}

unit_test_deps = [
  "$NEARLINK_ROOT/ipc_parcel:nearlink_ipc_parcel",
  "$NEARLINK_ROOT/utils:nearlink_utils",
  "$NEARLINK_ROOT/frameworks/native:nearlink_framework",
  "$NEARLINK_ROOT/services/common:nearlink_service_common",
  "$NEARLINK_ROOT/services/device_manager:nearlink_device_manager",
  "$NEARLINK_ROOT/services/service:nearlink_service_impl",
  "$NEARLINK_ROOT/services/stack:nearlink_stack",
  "$NEARLINK_ROOT/services/stack/src/sdf:nearlink_stack_sdf",
  "$NEARLINK_ROOT/services/server:nearlink_server_static_tdd",
  "${nearlink_test_utils_path}:test_utils_static",
]

unit_test_external_deps = [
  "c_utils:utils",
  "hilog:libhilog",
  "safwk:system_ability_fwk",
  "samgr:samgr_proxy",
  "huks:libhukssdk",
  "preferences:native_preferences",
  "access_token:libaccesstoken_sdk",
  "access_token:libtokenid_sdk",
  "googletest:gmock_main",
]

test_out_path = "nearlink_service/nearlink_service"

ohos_unittest("nl_ssap_server_service_test") {
  module_out_path = test_out_path

  branch_protector_ret = "pac_ret"  # Enable PAC CFI
  sanitize = {
    cfi = true                             # Enable/disable control flow integrity detection
    boundary_sanitize = true               # Enable boundary san detection
    cfi_cross_dso = true                   # Cross-SO CFI Checks
    integer_overflow = true                # Enable integer overflow detection
    ubsan = true                           # Enable some Ubsan options
    debug = true
  }

  sources = [
    "$NEARLINK_ROOT/test/unittest/services_test/service_test/ssap_server_test/ssap_server_service_test.cpp",
    "$NEARLINK_ROOT/test/unittest/services_test/service_test/ssap_server_test/iposl_ssap_probe_test.cpp",
  ]
  sources += [ "$MOCK_HOST_SERVER_FILE_TDD/mock_nearlink_host_server.cpp" ]

  configs = [ ":nl_ssap_server_service_unit_test_config" ]
  configs += ["${nearlink_test_utils_path}:test_utils_config"]

  deps = unit_test_deps

  external_deps = unit_test_external_deps
  external_deps += [ "ffrt:libffrt" ]

  part_name = "nearlink"
  subsystem_name = "communication"
}

group("nl_ssap_server_service_unittest") {
  testonly = true
  deps = [
    ":nl_ssap_server_service_test",
  ]
}